---

workshop_id: UOBT3DS20210418_01
topic: train-the-trainer
title: Train-the-Trainer - Data Sharing
instructors: [Matt Jaquiery, Jackie Thompson, Emma Wilson]
instructor_emails:
  - matt.jaquiery@psy.ox.ac.uk
  - jackie.thompson@bristol.ac.uk
  - Emma.Wilson@ed.ac.uk
helpers: []
# A list of hh|mm time formats [avoids jekyll auto-conversion].
# Only days with scheduled items get a start time.
# Days which can't be matched will use the first entry.
start_times: ["09|00"]
# list of files in _includes/install_instructions to use in the setup page
setup_files: []
language: en
venue:
address:
country:
latitude:
longitude:
start_date:
collaborative_notes: https://docs.google.com/document/d/1XB2o22aRACYNlaGp9cg1gMo4qm1wuomCOkXl0T3RMNI/edit?usp=sharing
eventbrite:
# list of files in path _includes/intro/* .md files can be customised; .html files cannot be customised. Files with an initial _ are ignored.
optional_intro_sections: []

# Custom but fixed fields
kind: workshop
ukrn_email: ORT@ukrn.org
ukrn_site: https://ukrn.org/
repository: <USERNAME>/<PROJECT>
carpentries_site: https://carpentries.org/
pre_survey: https://docs.google.com/forms/d/e/1FAIpQLSeqcrCGwbaNqLR9ehdWpUL2ydNzAYBgD81CJto5vRorBJMU1A/viewform?usp=pp_url&entry.2087576176=
post_survey: https://docs.google.com/forms/d/e/1FAIpQLSd2tLCqUGKPq0mLzHFReO8YLkcekZRMnC_xLF004lIAi0Bv4Q/viewform?usp=pp_url&entry.579599320=
code_of_conduct: https://cpb-eu-w2.wpmucdn.com/blogs.bristol.ac.uk/dist/b/631/files/2020/07/Code-of-Conduct-extracted-from-UKRN-ToR-v3.2.pdf

ukrn_or_template: https://ukrn-orr.netlify.app/workshop-template_ds.html
ukrn_or_builder: https://ukrn-wb.netlify.app/
ukrn_or_browser: https://ukrn-orr.netlify.app/
ukrn_or_resources: https://docs.google.com/spreadsheets/d/1cqsyS6RWQ38dU0Jc_ZyENZjRTFLj96AsiZVM4oxDWBA/edit?usp=sharing
workshop_admin_doc: https://docs.google.com/document/d/1qsRcsgqSL9zfmIymruD7Z3ZoIZhm9rix2mq0v_E5nDc/edit

# Fixed fields
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  episodes_rmd:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

exclude:
  - Makefile
  - bin/
  - .Rproj.user/
highlighter: rouge
